

export const SET_USER_TYPE="SET_USER_TYPE"
export const SET_USER="SET_USER"
export const SET_CURRENTLY_OCCUPIED="CURRENTLY_OCCUPIED"
export const SET_CURRENTLY_OCCUPIED_APPLICATION="CURRENTLY_OCCUPIED_APPLICATION"
export const SET_REVIEW_MODAL_APPLICATION="SET_REVIEW_MODAL_APPLICATION"
export const SET_REVIEW_MODAL_VISIBILITY="SET_REVIEW_MODAL_VISIBILITY"